### ISSUE TITLE
Does it update order page in admin?

### ISSUE THREAD

**Issue by antosha33** [begateway/opencart-3-payment-module#3]
I made a test success payment with this plugin in test mode. Everything is ok, but i don't see new order in my admin panel.. what's wrong? Hmm.. it seems to me that it depends on callback function in controller... do i need to edit it or it will work in production?

**Comment by avsh** [comment]
Hello! Try to update .htaccess file adding one of below statements after `RewriteEngine On`

    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule .* - [E=REDIRECT_HTTP_AUTHORIZATION:%{HTTP:Authorization}]

**Comment by antosha33** [comment]
it works. Thanks
