### ISSUE TITLE
Чтение ошибки и номера ошибки из закрытой сессии

### ISSUE THREAD

**Issue by YulyaKukareko** [begateway/opencart-3-payment-module#9]
В файле begateway.php (::132) происходит вызов curl_error($curl) и curl_errno($curl) после вызова curl_close($curl), что приводит к чтению пустого потока
`    curl_close($curl);

    if (!$response) {
      $this->log->write('Payment token request failed: ' . curl_error($curl) . '(' . curl_errno($curl) . ')');
      return false;
    }`

**Comment by avsh** [comment]
Исправлено в версии 3.0.3

https://github.com/begateway/opencart-3-payment-module/tree/3.0.3
